# # Discovery + Loadbalancing

# apiVersion: v1
# kind: Service
# metadata:
#   name: springboot
# spec:
#   # Defines which pod are going to be represented by this service
#   selector:
#     app: springboot
#   # Define which ports u are exposing for this service
#   # it means it is going to accept traffic at port 80
#   # and forwards traffic to 8080 for pods
#   ports:
#   - name: http
#     port: 80
#     targetPort: 8080
#   type: LoadBalancer
#   # type: ClusterIP # will only be accessible in the internal cluster - private services

# ---

# # Discovery + Loadbalancing

# apiVersion: v1
# kind: Service
# metadata:
#   name: nodejs
# spec:
#   # Defines which pod are going to be represented by this service
#   selector:
#     app: nodejs
#   # Define which ports u are exposing for this service
#   # it means it is going to accept traffic at port 80
#   # and forwards traffic to 8080 for pods
#   ports:
#   - name: http
#     port: 80
#     targetPort: 8080
#   type: LoadBalancer

# # ---
# # apiVersion: v1
# # kind: Service
# # metadata:
# #   name: queue
# # spec:
# #   selector:
# #     app: queue
# #     version: "0"
# #   ports:
# #   - name: http
# #     port: 8161
# #     nodePort: 30010
# #   type: NodePort
