apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-kubernetes-routing-rules
spec:
  rules:
    - host: innowashere.com
      http:
        paths:
        - path: /springboot
          pathType: Prefix
          backend:
            service:
              name: hello-springboot
              port: 
                number: {{ .Values.app.port }}
        - path: /nodejs
          pathType: Prefix
          backend:
            service:
              name: hello-nodejs
              port: 
                number: {{ .Values.app.port }}