# Default values for hello-kubernetes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1
imagePullPolicy: Always
app:
  name: hello-nodejs
  port: 8081
  endpointPrefix: nodejs
  imageBlueTagLocation: innoirvingdev/hello-nodejs:blue
  imageGreenTagLocation: innoirvingdev/hello-nodejs:green
  nodePort: 300801